version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"
    environment:
      - DB_HOST=db
      - DB_NAME=cartorios
      - DB_USER=cesar
      - DB_PASS=cesar123
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=cartorios
      - POSTGRES_USER=cesar
      - POSTGRES_PASSWORD=cesar123
    ports:
      - "5432:5432"
    volumes:
    - ./dbdata:/var/lib/postgresql/data
