# Generated by Django 3.2.8 on 2021-10-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True)),
                ('cns', models.CharField(blank=True, max_length=50, null=True)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('nome_oficial', models.CharField(blank=True, max_length=700, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=700, null=True)),
                ('nome_titular', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_substituto', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_juiz', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_atualizacao', models.DateField(blank=True, null=True)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=100, null=True)),
                ('area_abrangencia', models.CharField(blank=True, max_length=700, null=True)),
                ('atribuicoes', models.CharField(blank=True, max_length=700, null=True)),
                ('comarca', models.CharField(blank=True, max_length=255, null=True)),
                ('entrancia', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.CharField(blank=True, max_length=700, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('home_page', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=700, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('uf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
            ],
            options={
                'verbose_name_plural': 'Cartorios',
            },
        ),
    ]
