# Generated by Django 3.2.8 on 2021-10-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorios',
            name='nome_juiz',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='nome_substituto',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='nome_titular',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
