# Generated by Django 3.2.8 on 2021-10-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211021_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorios',
            name='bairro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='municipio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
